[general]
live_config_reload = true
import = ["~/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Inconsolata"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9

[debug]
renderer = "None"
