# 1. General
set -g default-terminal "screen-256color"
set -as terminal-overrides ",xterm*:Tc"

set -g history-limit 1000000

# Faster escape sequences
set -sg escape-time 10

# Start window numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows after closing
set -g renumber-windows on

# Automatically rename windows
set -g automatic-rename on

# Reload config
bind r source-file "$HOME/.tmux.conf" \; display-message "tmux config reloaded"

# 2. Prefix
# Prefer C-a for local tmux sessions, and C-b for remote.
# Saves the dance of doing C-b C-b for each command too.
if-shell 'test -n "$SSH_TTY"' {
    set -g prefix C-b
    bind C-b send-prefix

    set -g status-left "[REMOTE] "

    set -g status-bg blue
    set -g status-fg white
} {
    set -g prefix C-a
    unbind C-b
    bind C-a send-prefix

    set -g status-left "[LOCAL] "

    # Default Dracula-ish background for local
    set -g status-bg '#282a36'
    set -g status-fg '#bd93f9'
}

# 3. Mouse
setw -g mouse on

# 4. Splits
# Easier split keys, open panes in current directory
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

# 5. Vim mode
set-window-option -g mode-keys vi

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Enter copy mode with Prefix + Escape (or keep default Prefix + [ )
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind -T copy-mode-vi MouseDragEnd1Pane

# 6. Appearance

# 7. Misc Keybindings
# Smart pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
